# -*- coding: utf-8 -*-
"""Walmart_Sales_Data(AI_Ml).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/dahiyayogita77-ops/Walmart-Sales-Data-AI-ML-/blob/main/Walmart_Sales_Data(AI_Ml).ipynb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
uploaded = files.upload()

df = pd.read_csv("walmart-sales-dataset-of-45stores.csv")
df.head()

# ~ Data Cleaning
# Check Missing Values
print("Missing values:\n", df.isnull().sum())

#Handle Missing Values
# Fill numerical columns with mean
for col in df.select_dtypes(include=['float64', 'int64']):
    df[col].fillna(df[col].mean(), inplace=True)

# Fill categorical columns with mode
for col in df.select_dtypes(include=['object']):
    df[col].fillna(df[col].mode()[0], inplace=True)

#Remove Duplicates
# Count duplicates
duplicates = df.duplicated().sum()
print("Number of duplicate rows:", duplicates)

# Remove duplicates
df = df.drop_duplicates()

# Verify removal
print("Duplicates after removal:", df.duplicated().sum())

#Convert Data Types
# Convert Date column to datetime
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)
# Extract useful time features
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Week'] = df['Date'].dt.isocalendar().week

#Rename Columns (optional for clarity)
df.columns = df.columns.str.strip().str.replace(" ", "_")

#Feature Engineering
# Example: Sales per store per week
df['Sales_per_Store'] = df['Weekly_Sales'] / df['Store']

# Holiday flag conversion (if exists)
if 'Holiday_Flag' in df.columns:
    df['Holiday_Flag'] = df['Holiday_Flag'].astype('category')

# ~Exploratory Data Analysis (EDA)
#Total Sales
total_sales = df['Weekly_Sales'].sum()
print("Total Sales:", total_sales)

#Sales by Store
store_sales = df.groupby('Store')['Weekly_Sales'].sum().sort_values(ascending=False)
print(store_sales.head())

#Monthly Sales Trend
monthly_sales = df.groupby('Month')['Weekly_Sales'].sum()

monthly_sales.plot(kind='line')
plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Sales")
plt.show()

#Holiday vs Non-Holiday Sales
if 'Holiday_Flag' in df.columns:
    holiday_sales = df.groupby('Holiday_Flag')['Weekly_Sales'].mean()
    print(holiday_sales)

#Correlation Analysis
correlation = df.corr(numeric_only=True)

print(correlation)

# Heatmap
import seaborn as sns
sns.heatmap(correlation, annot=True)
plt.show()

#df.to_csv("cleaned_walmart_data.csv", index=False)
df.to_csv("cleaned_walmart_data.csv", index=False)

#Sales Prediction model
#Libraries
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

#Prepare Data for ML
#Select Features (X) and Target (y)
# Features (independent variables)
X = df[['Store', 'Fuel_Price', 'CPI', 'Unemployment', 'Month', 'Year']]

# Target (what we predict)
y = df['Weekly_Sales']

#Convert Categorical Data (if needed)
# Convert Holiday_Flag if present
if 'Holiday_Flag' in df.columns:
    X = pd.get_dummies(X.join(df['Holiday_Flag']), drop_first=True)

#Split Data (Train/Test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

#Train Model (Linear Regression)
model = LinearRegression()
model.fit(X_train, y_train)

#Make Predictions
y_pred = model.predict(X_test)

#Evaluate Model
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error:", mae)
print("R2 Score:", r2)

#Compare Actual vs Predicted
plt.scatter(y_test, y_pred)
plt.xlabel("Actual Sales")
plt.ylabel("Predicted Sales")
plt.title("Actual vs Predicted Sales")
plt.show()

#Advanced Model (Better Accuracy)
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print("Random Forest R2:", r2_score(y_test, y_pred_rf))

#Feature Importance (Very Impressive)
importance = pd.Series(rf.feature_importances_, index=X.columns)
importance.sort_values().plot(kind='barh')
plt.title("Feature Importance")
plt.show()

